# Generated by Django 4.2.8 on 2026-01-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsource',
            name='status',
        ),
    ]
