# Generated by Django 4.2.8 on 2026-01-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_channels', '0003_add_subsource_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='sla_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='SLA override in minutes (null = use channel default)', null=True),
        ),
    ]
