# Generated by Django 5.2.10 on 2026-01-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_channels', '0006_remove_subsource_and_cleanup'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='Linked MS user (for BH Mortgage Team self-sourcing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_sources', to='users.user'),
        ),
    ]
