# Generated by Django 5.2.10 on 2026-01-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_channels', '0008_channel_owner_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
