# Generated by Django 5.2.10 on 2026-01-19 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name for easy identification', max_length=100)),
                ('category', models.CharField(choices=[('greeting', 'Greeting'), ('followup', 'Follow-up'), ('documentation', 'Documentation'), ('loan_update', 'Loan Update'), ('general', 'General')], default='general', help_text='Category for organizing templates', max_length=20)),
                ('content', models.TextField(help_text='Message content with {variable} placeholders')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the template is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='users.user')),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['category', 'name'],
            },
        ),
    ]
