# Generated by Django 5.2.10 on 2026-01-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='category',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('followup', 'Follow-up'), ('documentation', 'Documentation'), ('application_update', 'Application Update'), ('general', 'General')], default='general', help_text='Category for organizing templates', max_length=20),
        ),
    ]
