# Generated by Django 4.2.8 on 2026-01-13 06:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Channel name (e.g., Performance Marketing)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description of this channel')),
                ('is_trusted', models.BooleanField(default=False, help_text='Trusted channels create Clients directly; untrusted create Leads')),
                ('default_sla_minutes', models.PositiveIntegerField(blank=True, help_text='Default SLA in minutes for this channel', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this channel is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Source name (e.g., Google Search)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(help_text='Parent channel', on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='channels.channel')),
            ],
            options={
                'db_table': 'sources',
                'ordering': ['name'],
                'unique_together': {('channel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Sub-source name (e.g., campaign name, agent name)', max_length=100)),
                ('sla_minutes', models.PositiveIntegerField(blank=True, help_text='SLA override in minutes (null = use channel default)', null=True)),
                ('status', models.CharField(choices=[('incubation', 'Incubation'), ('active', 'Active'), ('paused', 'Paused')], default='active', help_text='Sub-source status (primarily for campaigns)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sub-source is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, help_text='Linked MS user (for BH Mortgage Team self-sourcing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_sub_sources', to='users.user')),
                ('source', models.ForeignKey(help_text='Parent source', on_delete=django.db.models.deletion.CASCADE, related_name='sub_sources', to='channels.source')),
            ],
            options={
                'db_table': 'sub_sources',
                'ordering': ['name'],
                'unique_together': {('source', 'name')},
            },
        ),
    ]
