# Generated by Django 4.2.8 on 2026-01-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_remove_subsource_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsource',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subsource',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('incubation', 'Incubation'), ('live', 'Live'), ('paused', 'Paused')], default='incubation', help_text='Status: active/inactive for trusted, incubation/live/paused for untrusted', max_length=20),
        ),
    ]
