# Generated by Django 5.2.10 on 2026-01-20 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisition_channels', '0004_add_source_sla'),
        ('leads', '0002_add_campaign_tracking'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ycloud_campaign_id', models.CharField(blank=True, help_text='YCloud campaign ID for reference', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to='users.user')),
                ('sub_source', models.ForeignKey(blank=True, help_text='Attribution sub-source for leads from this campaign', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='acquisition_channels.subsource')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(help_text='YCloud template name (e.g., revo_test_initial_v1)', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Human-readable name for display', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sequence_order', models.PositiveIntegerField(default=0, help_text='Order in the campaign journey (0 = first)')),
                ('buttons', models.JSONField(blank=True, default=list, help_text='List of button objects: [{"text": "Yes", "payload": "Yes"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Template',
                'verbose_name_plural': 'Campaign Templates',
                'ordering': ['sequence_order'],
                'unique_together': {('campaign', 'template_name')},
            },
        ),
        migrations.CreateModel(
            name='CampaignJourneyStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField(help_text='Order of this step in the journey (1 = first)')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual Send'), ('tag_added', 'Tag Added'), ('button_click', 'Button Click'), ('text_reply', 'Text Reply')], default='manual', max_length=50)),
                ('trigger_value', models.CharField(blank=True, help_text='Tag name, button payload, or text pattern that triggers this step', max_length=255)),
                ('adds_tags', models.JSONField(blank=True, default=list, help_text='Tags to add when this step is reached: ["tag1", "tag2"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_steps', to='campaigns.campaign')),
                ('template', models.ForeignKey(blank=True, help_text='Template sent when this step is triggered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by_steps', to='campaigns.campaigntemplate')),
            ],
            options={
                'verbose_name': 'Campaign Journey Step',
                'verbose_name_plural': 'Campaign Journey Steps',
                'ordering': ['step_order'],
                'unique_together': {('campaign', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='CampaignTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(help_text='YCloud tag name (e.g., revo_test_interested)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Human-readable name for display', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher priority = more important for status calculation')),
                ('is_positive', models.BooleanField(default=True, help_text='True = interested/qualified, False = not interested/disqualified')),
                ('is_terminal', models.BooleanField(default=False, help_text='True = journey complete (completed or dropped)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Tag',
                'verbose_name_plural': 'Campaign Tags',
                'ordering': ['priority'],
                'unique_together': {('campaign', 'tag_name')},
            },
        ),
        migrations.CreateModel(
            name='LeadCampaignEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('progressing', 'Progressing'), ('stalled', 'Stalled'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='campaigns.campaign')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_enrollments', to='campaigns.campaignjourneystep')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead Campaign Enrollment',
                'verbose_name_plural': 'Lead Campaign Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('lead', 'campaign')},
            },
        ),
    ]
