# Generated by Django 5.2.10 on 2026-01-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_auto_discovered',
            field=models.BooleanField(default=False, help_text='True if this campaign was auto-discovered from YCloud'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this campaign was synced from YCloud', null=True),
        ),
        migrations.AddField(
            model_name='campaigntag',
            name='is_auto_discovered',
            field=models.BooleanField(default=False, help_text='True if this tag was auto-discovered from webhook'),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='is_auto_discovered',
            field=models.BooleanField(default=False, help_text='True if this template was auto-discovered from YCloud'),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='ycloud_template_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw template data from YCloud API'),
        ),
    ]
