# Generated by Django 5.2.10 on 2026-01-19 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0006_alter_client_residency_alter_coapplicant_residency'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the message', primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', help_text='Direction of the message (outbound/inbound)', max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('image', 'Image'), ('document', 'Document')], default='text', help_text='Type of message', max_length=20)),
                ('content', models.TextField(help_text='Message content/body')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', help_text='Delivery status of the message', max_length=20)),
                ('ycloud_message_id', models.CharField(blank=True, default='', help_text='Message ID from YCloud API response', max_length=255)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if sending failed')),
                ('from_number', models.CharField(help_text='Sender phone number', max_length=20)),
                ('to_number', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was created')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the message was sent to YCloud', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the message was delivered', null=True)),
                ('client', models.ForeignKey(help_text='Client this message is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='clients.client')),
                ('sent_by', models.ForeignKey(blank=True, help_text='User who sent this message (for outbound messages)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_messages', to='users.user')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='wa_client_created_idx'), models.Index(fields=['ycloud_message_id'], name='wa_ycloud_msg_idx'), models.Index(fields=['status'], name='wa_status_idx')],
            },
        ),
    ]
