# Generated by Django 4.2.8 on 2026-01-13 09:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the client', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the client', max_length=255)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('email', models.EmailField(blank=True, default='', help_text='Email address (optional)', max_length=255, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('emirates_id', models.CharField(blank=True, default='', help_text='Emirates ID number (optional)', max_length=20)),
                ('residency', models.CharField(choices=[('uae_resident', 'UAE Resident'), ('non_resident', 'Non-Resident')], default='uae_resident', help_text='Residency status', max_length=20)),
                ('visa_type', models.CharField(blank=True, choices=[('employment', 'Employment'), ('investor', 'Investor'), ('golden', 'Golden'), ('retirement', 'Retirement'), ('other', 'Other')], default='', help_text='Visa type (optional)', max_length=20)),
                ('application_type', models.CharField(choices=[('single', 'Single'), ('joint', 'Joint')], default='single', help_text='Single or joint application', max_length=10)),
                ('is_first_property', models.BooleanField(default=True, help_text='Whether this is the first property purchase')),
                ('employment_type', models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed')], default='salaried', help_text='Employment type', max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly salary amount', max_digits=12)),
                ('company_name', models.CharField(blank=True, default='', help_text='Employer company name (optional)', max_length=255)),
                ('cc_1_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit card 1 limit (optional)', max_digits=12, null=True)),
                ('cc_2_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit card 2 limit (optional)', max_digits=12, null=True)),
                ('cc_3_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit card 3 limit (optional)', max_digits=12, null=True)),
                ('cc_4_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit card 4 limit (optional)', max_digits=12, null=True)),
                ('cc_5_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit card 5 limit (optional)', max_digits=12, null=True)),
                ('auto_loan_emi', models.DecimalField(blank=True, decimal_places=2, help_text='Auto loan EMI (optional)', max_digits=12, null=True)),
                ('personal_loan_emi', models.DecimalField(blank=True, decimal_places=2, help_text='Personal loan EMI (optional)', max_digits=12, null=True)),
                ('existing_mortgage_emi', models.DecimalField(blank=True, decimal_places=2, help_text='Existing mortgage EMI (optional)', max_digits=12, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('ready', 'Ready'), ('off_plan', 'Off-Plan')], default='', help_text='Property type interest (optional)', max_length=20)),
                ('transaction_type', models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('refinance', 'Refinance'), ('equity_release', 'Equity Release')], default='', help_text='Transaction type interest (optional)', max_length=20)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, help_text='Property value (optional)', max_digits=12, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Requested loan amount (optional)', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about the client')),
                ('timeline', models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('1_3_months', '1-3 Months'), ('3_6_months', '3-6 Months'), ('exploring', 'Exploring')], default='', help_text='Timeline for property purchase', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('declined', 'Declined'), ('not_proceeding', 'Not Proceeding')], default='active', help_text='Current status of the client', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the client was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the client was last updated')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoApplicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the co-applicant', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the co-applicant', max_length=255)),
                ('phone', models.CharField(blank=True, default='', help_text='Phone number', max_length=20)),
                ('email', models.EmailField(blank=True, default='', help_text='Email address (optional)', max_length=255, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('emirates_id', models.CharField(blank=True, default='', help_text='Emirates ID number (optional)', max_length=20)),
                ('residency', models.CharField(choices=[('uae_resident', 'UAE Resident'), ('non_resident', 'Non-Resident')], default='uae_resident', help_text='Residency status', max_length=20)),
                ('visa_type', models.CharField(blank=True, choices=[('employment', 'Employment'), ('investor', 'Investor'), ('golden', 'Golden'), ('retirement', 'Retirement'), ('other', 'Other')], default='', help_text='Visa type (optional)', max_length=20)),
                ('employment_type', models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed')], default='salaried', help_text='Employment type', max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly salary amount', max_digits=12)),
                ('company_name', models.CharField(blank=True, default='', help_text='Employer company name (optional)', max_length=255)),
                ('cc_1_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit card 1 limit (optional)', max_digits=12, null=True)),
                ('cc_2_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit card 2 limit (optional)', max_digits=12, null=True)),
                ('cc_3_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit card 3 limit (optional)', max_digits=12, null=True)),
                ('cc_4_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit card 4 limit (optional)', max_digits=12, null=True)),
                ('cc_5_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit card 5 limit (optional)', max_digits=12, null=True)),
                ('auto_loan_emi', models.DecimalField(blank=True, decimal_places=2, help_text='Auto loan EMI (optional)', max_digits=12, null=True)),
                ('personal_loan_emi', models.DecimalField(blank=True, decimal_places=2, help_text='Personal loan EMI (optional)', max_digits=12, null=True)),
                ('existing_mortgage_emi', models.DecimalField(blank=True, decimal_places=2, help_text='Existing mortgage EMI (optional)', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the co-applicant was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the co-applicant was last updated')),
                ('client', models.OneToOneField(help_text='The primary client this co-applicant is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='co_applicant', to='clients.client')),
            ],
            options={
                'db_table': 'co_applicants',
                'ordering': ['-created_at'],
            },
        ),
    ]
