# Generated by Django 4.2.8 on 2026-01-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('channels', '0004_add_source_sla'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='converted_from_lead',
            field=models.ForeignKey(blank=True, help_text='Lead this client was converted from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_clients', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='client',
            name='sub_source',
            field=models.ForeignKey(help_text='Sub-source where client originated', on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='channels.subsource'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['sub_source'], name='clients_sub_source_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='clients_created_at_idx'),
        ),
    ]
