# Generated by Django 4.2.8 on 2026-01-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nationality',
            field=models.CharField(blank=True, default='', help_text='Nationality', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='total_addbacks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total addbacks (rental income, bonuses, etc.)', max_digits=12, null=True),
        ),
    ]
