# Generated by Django 4.2.8 on 2026-01-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_date_of_birth_client_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_first_property',
        ),
        migrations.RemoveField(
            model_name='client',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='property_value',
        ),
        migrations.RemoveField(
            model_name='client',
            name='transaction_type',
        ),
    ]
