# Generated by Django 4.2.8 on 2026-01-18
# Migration to add SLA tracking fields to Client model

from django.db import migrations, models
import django.db.models.deletion


def set_assigned_to_from_created_by(apps, schema_editor):
    """
    Data migration to set assigned_to = created_by for existing clients.
    Since we don't have created_by stored directly, we try to use the audit log.
    Uses raw SQL to avoid model instantiation issues.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Update clients where assigned_to is null using audit log data
        cursor.execute("""
            UPDATE clients
            SET assigned_to_id = (
                SELECT user_id FROM audit_logs
                WHERE audit_logs.table_name = 'clients'
                AND audit_logs.record_id = clients.id
                AND audit_logs.action = 'CREATE'
                LIMIT 1
            )
            WHERE assigned_to_id IS NULL
        """)


def reverse_set_assigned_to(apps, schema_editor):
    """Reverse migration - set assigned_to to null."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("UPDATE clients SET assigned_to_id = NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_is_first_property_to_case'),
        ('users', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        # Add assigned_to field
        migrations.AddField(
            model_name='client',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                help_text='User assigned to this client',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_clients',
                to='users.user',
            ),
        ),
        # Add first_contact_completed_at field
        migrations.AddField(
            model_name='client',
            name='first_contact_completed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When First Contact SLA was satisfied (document upload, note, state change, or case created)',
                null=True,
            ),
        ),
        # Add index for assigned_to
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_to'], name='clients_assigned_to_idx'),
        ),
        # Data migration to backfill assigned_to from audit log
        migrations.RunPython(set_assigned_to_from_created_by, reverse_set_assigned_to),
    ]
