# Generated by Django 4.2.8 on 2026-01-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_sla_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='developer',
            field=models.CharField(blank=True, default='', help_text='Developer name (for off-plan properties)', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='emirate',
            field=models.CharField(choices=[('dubai', 'Dubai'), ('abu_dhabi', 'Abu Dhabi'), ('sharjah', 'Sharjah'), ('ajman', 'Ajman'), ('ras_al_khaimah', 'Ras Al Khaimah'), ('umm_al_quwain', 'Umm Al Quwain'), ('fujairah', 'Fujairah')], default='dubai', help_text='Emirate where property is located', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='is_first_property',
            field=models.BooleanField(default=True, help_text="Whether this is the client's first property in UAE"),
        ),
        migrations.AddField(
            model_name='client',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Requested loan amount in AED', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='property_category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', help_text='Property category (residential/commercial)', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='property_type',
            field=models.CharField(choices=[('ready', 'Ready'), ('off_plan', 'Off-Plan')], default='ready', help_text='Property type (ready/off-plan)', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Property value in AED', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tenure_months',
            field=models.PositiveIntegerField(default=0, help_text='Additional months for loan tenure (0-11)'),
        ),
        migrations.AddField(
            model_name='client',
            name='tenure_years',
            field=models.PositiveIntegerField(default=20, help_text='Loan tenure in years (1-25)'),
        ),
        migrations.AddField(
            model_name='client',
            name='transaction_type',
            field=models.CharField(choices=[('primary_purchase', 'Primary Purchase'), ('resale', 'Resale'), ('buyout_equity', 'Buyout + Equity'), ('buyout', 'Buyout'), ('equity', 'Equity')], default='primary_purchase', help_text='Type of transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='residency',
            field=models.CharField(choices=[('uae_national', 'UAE National'), ('uae_resident', 'UAE Resident'), ('non_resident', 'Non-Resident')], default='uae_resident', help_text='Residency status', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('declined', 'Declined'), ('not_proceeding', 'Not Proceeding')], default='active', help_text='Current status of the client', max_length=20),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='residency',
            field=models.CharField(choices=[('uae_national', 'UAE National'), ('uae_resident', 'UAE Resident'), ('non_resident', 'Non-Resident')], default='uae_resident', help_text='Residency status', max_length=20),
        ),
    ]
