# Generated by Django 5.2.10 on 2026-01-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_sla_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='residency',
            field=models.CharField(choices=[('uae_national', 'UAE National'), ('uae_resident', 'UAE Resident'), ('non_resident', 'Non-Resident')], default='uae_resident', help_text='Residency status', max_length=20),
        ),
        migrations.AlterField(
            model_name='coapplicant',
            name='residency',
            field=models.CharField(choices=[('uae_national', 'UAE National'), ('uae_resident', 'UAE Resident'), ('non_resident', 'Non-Resident')], default='uae_resident', help_text='Residency status', max_length=20),
        ),
    ]
