# Generated by Django 4.2.8 on 2026-01-22 07:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_add_property_loan_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientExtraDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='', help_text='Marital status', max_length=20)),
                ('spouse_name', models.CharField(blank=True, default='', help_text='Spouse name (if married)', max_length=255)),
                ('spouse_contact', models.CharField(blank=True, default='', help_text='Spouse contact number', max_length=50)),
                ('dependents', models.PositiveIntegerField(blank=True, help_text='Number of dependents', null=True)),
                ('children_count', models.PositiveIntegerField(blank=True, help_text='Number of children', null=True)),
                ('children_in_school', models.PositiveIntegerField(blank=True, help_text='Number of children in school', null=True)),
                ('qualification', models.CharField(blank=True, default='', help_text='Education qualification', max_length=100)),
                ('mailing_address', models.TextField(blank=True, default='', help_text='Mailing/correspondence address')),
                ('mother_maiden_name', models.CharField(blank=True, default='', help_text="Mother's maiden name (for bank security)", max_length=100)),
                ('job_title', models.CharField(blank=True, default='', help_text='Job title (salaried)', max_length=100)),
                ('company_industry', models.CharField(blank=True, default='', help_text='Company industry/sector', max_length=100)),
                ('years_in_occupation', models.PositiveIntegerField(blank=True, help_text='Years in current occupation (salaried)', null=True)),
                ('years_in_current_company', models.PositiveIntegerField(blank=True, help_text='Years in current company (salaried)', null=True)),
                ('years_in_business', models.PositiveIntegerField(blank=True, help_text='Years in business (self-employed)', null=True)),
                ('company_employee_count', models.PositiveIntegerField(blank=True, help_text='Number of employees in organization', null=True)),
                ('office_address', models.TextField(blank=True, default='', help_text='Office address')),
                ('office_po_box', models.CharField(blank=True, default='', help_text='Office PO Box', max_length=20)),
                ('office_landline', models.CharField(blank=True, default='', help_text='Office landline number', max_length=20)),
                ('work_email', models.EmailField(blank=True, default='', help_text='Work email address (salaried)', max_length=255)),
                ('company_hr_email', models.EmailField(blank=True, default='', help_text='Company HR email for verification (salaried)', max_length=255)),
                ('ref_1_name', models.CharField(blank=True, default='', help_text='Reference 1 name', max_length=255)),
                ('ref_1_relationship', models.CharField(blank=True, default='', help_text='Reference 1 relationship', max_length=100)),
                ('ref_1_mobile', models.CharField(blank=True, default='', help_text='Reference 1 mobile', max_length=20)),
                ('ref_2_name', models.CharField(blank=True, default='', help_text='Reference 2 name', max_length=255)),
                ('ref_2_relationship', models.CharField(blank=True, default='', help_text='Reference 2 relationship', max_length=100)),
                ('ref_2_mobile', models.CharField(blank=True, default='', help_text='Reference 2 mobile', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the extra details were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the extra details were last updated')),
                ('client', models.OneToOneField(help_text='The client this extra details belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='extra_details', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Extra Details',
                'verbose_name_plural': 'Client Extra Details',
                'db_table': 'client_extra_details',
            },
        ),
    ]
