# Generated by Django 5.2.10 on 2026-01-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_residency_alter_coapplicant_residency'),
        ('clients', '0007_add_client_extra_details'),
    ]

    operations = [
    ]
