# Generated by Django 4.2.8 on 2026-01-18 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0008_remove_product_field'),
        ('clients', '0004_add_is_first_property_to_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the document', primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True, default='', help_text='URL to the uploaded file', max_length=1024)),
                ('file_name', models.CharField(blank=True, default='', help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_format', models.CharField(blank=True, default='', help_text='File format (extension)', max_length=10)),
                ('applicant_role', models.CharField(choices=[('primary', 'Primary'), ('co_applicant', 'Co-Applicant')], default='primary', help_text='Which applicant this document belongs to', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('verified', 'Verified')], default='pending', help_text='Upload status of the document', max_length=10)),
                ('uploaded_via', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp')], default='web', help_text='Source of the upload', max_length=10)),
                ('uploaded_at', models.DateTimeField(blank=True, help_text='When the document was uploaded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
            ],
            options={
                'db_table': 'case_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the document', primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True, default='', help_text='URL to the uploaded file', max_length=1024)),
                ('file_name', models.CharField(blank=True, default='', help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_format', models.CharField(blank=True, default='', help_text='File format (extension)', max_length=10)),
                ('applicant_role', models.CharField(choices=[('primary', 'Primary'), ('co_applicant', 'Co-Applicant')], default='primary', help_text='Which applicant this document belongs to', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('verified', 'Verified')], default='pending', help_text='Upload status of the document', max_length=10)),
                ('uploaded_via', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp')], default='web', help_text='Source of the upload', max_length=10)),
                ('uploaded_at', models.DateTimeField(blank=True, help_text='When the document was uploaded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
            ],
            options={
                'db_table': 'client_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the document type', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the document type', max_length=255)),
                ('level', models.CharField(choices=[('client', 'Client'), ('case', 'Case')], help_text='Document level (client or case)', max_length=10)),
                ('required', models.BooleanField(default=False, help_text='Whether this document is required')),
                ('description', models.TextField(blank=True, default='', help_text='Description of the document type')),
                ('applicant_type', models.CharField(choices=[('primary', 'Primary'), ('co_applicant', 'Co-Applicant'), ('both', 'Both')], default='both', help_text='Which applicant(s) this document applies to', max_length=15)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying in checklists')),
                ('is_system', models.BooleanField(default=False, help_text='Whether this is a system-defined document type (not deletable)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the document type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the document type was last updated')),
            ],
            options={
                'db_table': 'document_types',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['level'], name='document_types_level_idx'), models.Index(fields=['required'], name='document_types_required_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('name', 'level'), name='document_types_name_level_unique'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(help_text='Client this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='document_type',
            field=models.ForeignKey(help_text='Type of document', on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(help_text='Case this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='document_type',
            field=models.ForeignKey(help_text='Type of document', on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client'], name='client_docs_client_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['document_type'], name='client_docs_type_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['status'], name='client_docs_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['applicant_role'], name='client_docs_role_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['case'], name='case_docs_case_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['document_type'], name='case_docs_type_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['status'], name='case_docs_status_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['applicant_role'], name='case_docs_role_idx'),
        ),
    ]
