# Generated by Django 4.2.8 on 2026-01-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_seed_document_types'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documenttype',
            name='document_types_name_level_unique',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='category',
            field=models.CharField(blank=True, choices=[('salaried_uae_national', 'Salaried - UAE National'), ('self_employed_uae_national', 'Self-Employed - UAE National'), ('salaried_uae_resident', 'Salaried - UAE Resident'), ('self_employed_uae_resident', 'Self-Employed - UAE Resident'), ('salaried_non_resident', 'Salaried - Non-Resident'), ('self_employed_non_resident', 'Self-Employed - Non-Resident'), ('conditional', 'Conditional')], default='', help_text='Document category based on employment/residency type', max_length=30),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='condition',
            field=models.CharField(blank=True, default='', help_text='Condition when this document is required (for conditional documents)', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('name', 'level', 'category'), name='document_types_name_level_category_unique'),
        ),
    ]
