# Generated by Django 4.2.8 on 2026-01-13 09:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the case', primary_key=True, serialize=False)),
                ('application_type', models.CharField(choices=[('single', 'Single'), ('joint', 'Joint')], help_text='Single or joint application (copied from client)', max_length=10)),
                ('property_type', models.CharField(choices=[('ready', 'Ready'), ('off_plan', 'Off-Plan')], help_text='Property type (Ready or Off-Plan)', max_length=20)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('refinance', 'Refinance'), ('equity_release', 'Equity Release')], help_text='Transaction type (Purchase, Refinance, Equity Release)', max_length=20)),
                ('property_value', models.DecimalField(decimal_places=2, help_text='Property value amount', max_digits=12)),
                ('developer', models.CharField(blank=True, default='', help_text='Developer name (for off-plan properties)', max_length=255)),
                ('project_name', models.CharField(blank=True, default='', help_text='Project name (optional)', max_length=255)),
                ('location', models.CharField(blank=True, default='', help_text='Property location (optional)', max_length=255)),
                ('loan_amount', models.DecimalField(decimal_places=2, help_text='Loan amount requested', max_digits=12)),
                ('tenure_years', models.PositiveIntegerField(help_text='Loan tenure in years (5-25)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('bank', models.CharField(help_text='Bank name', max_length=100)),
                ('product', models.CharField(help_text='Bank product name', max_length=100)),
                ('rate_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], help_text='Rate type (Fixed or Variable)', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Interest rate percentage', max_digits=5)),
                ('stage', models.CharField(choices=[('processing', 'Processing'), ('document_collection', 'Document Collection'), ('bank_submission', 'Bank Submission'), ('bank_processing', 'Bank Processing'), ('offer_issued', 'Offer Issued'), ('offer_accepted', 'Offer Accepted'), ('property_valuation', 'Property Valuation'), ('final_approval', 'Final Approval'), ('property_transfer', 'Property Transfer'), ('on_hold', 'On Hold'), ('property_transferred', 'Property Transferred'), ('declined', 'Declined'), ('not_proceeding', 'Not Proceeding')], default='processing', help_text='Current stage of the case', max_length=30)),
                ('stage_changed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the stage was last changed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the case was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the case was last updated')),
            ],
            options={
                'verbose_name_plural': 'cases',
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
