# Generated by Django 4.2.8 on 2026-01-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(help_text='Client associated with this case', on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['stage'], name='cases_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['client'], name='cases_client_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='cases_created_at_idx'),
        ),
    ]
