# Generated by Django 4.2.8 on 2026-01-16 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the bank', primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(blank=True, help_text='External ID for reference', null=True, unique=True)),
                ('name', models.CharField(help_text='Bank name/title', max_length=255)),
                ('logo', models.URLField(blank=True, default='', help_text='Bank logo URL', max_length=500)),
                ('icon', models.URLField(blank=True, default='', help_text='Bank icon URL', max_length=500)),
                ('minimum_loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum loan amount in AED', max_digits=12, null=True)),
                ('maximum_loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum loan amount in AED', max_digits=12, null=True)),
                ('minimum_account_opening_duration_days', models.PositiveIntegerField(blank=True, help_text='Minimum days for account opening', null=True)),
                ('disbursal_turn_around_days', models.PositiveIntegerField(blank=True, help_text='Days for loan disbursal', null=True)),
                ('fol_turn_around_time_days', models.PositiveIntegerField(blank=True, help_text='Days for FOL turnaround', null=True)),
                ('valuation_turn_around_time_days', models.PositiveIntegerField(blank=True, help_text='Days for property valuation', null=True)),
                ('transfer_turn_around_time_days', models.PositiveIntegerField(blank=True, help_text='Days for property transfer', null=True)),
                ('total_expected_turn_around_time_days', models.PositiveIntegerField(blank=True, help_text='Total expected turnaround time in days', null=True)),
                ('has_early_settlement_fee', models.BooleanField(default=False, help_text='Whether early settlement fee applies')),
                ('early_settlement_fee_percentage', models.CharField(blank=True, default='', help_text='Early settlement fee percentage', max_length=20)),
                ('has_partial_settlement_fee', models.BooleanField(default=False, help_text='Whether partial settlement fee applies')),
                ('partial_settlement_fee_percentage', models.CharField(blank=True, default='', help_text='Partial settlement fee percentage', max_length=20)),
                ('life_insurance_payment_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='', help_text='Life insurance payment period', max_length=20)),
                ('property_insurance_payment_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='', help_text='Property insurance payment period', max_length=20)),
                ('supported_mortgage_types', models.JSONField(blank=True, default=list, help_text='List of supported mortgage types')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the bank is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the bank was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the bank was last updated')),
            ],
            options={
                'db_table': 'banks',
                'ordering': ['name'],
            },
        ),
    ]
