from django.db import migrations


BANKS_DATA = [
    {"external_id": "883a4cff-902f-40e3-b365-fa4bbd95acb8", "name": "Sharjah Islamic Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Sharjah%20Islamic%20Bank/sharjah_islamic_bank.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Sharjah%20Islamic%20Bank/sharjah_islamic_bank_ok.png", "supported_mortgage_types": ["islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "annually"},
    {"external_id": "30695c45-97cf-4d53-83f4-199318443af4", "name": "Abu Dhabi Commercial Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Abu%20Dhabi%20Commercial%20Bank/ADCBadcb.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Abu%20Dhabi%20Commercial%20Bank/adcb_ok.png", "minimum_loan_amount": 250000, "maximum_loan_amount": 24000000, "minimum_account_opening_duration_days": 1, "disbursal_turn_around_days": 4, "fol_turn_around_time_days": 4, "valuation_turn_around_time_days": 6, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 19, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "30%", "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "annually", "supported_mortgage_types": []},
    {"external_id": "5a2b51da-f5b5-4e0d-80de-9b488936f096", "name": "Alma", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Alma/Alma_logo.jpg", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Alma/Alma_logo.jpg", "supported_mortgage_types": ["conventional", "islamic", "best_rate"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "65ec938f-1ff0-477d-bad5-aeb02caa64fc", "name": "SCB - Private Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Standard%20Chartered%20Bank%20Business%20Banking/standard.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Standard%20Chartered%20Bank%20Business%20Banking/standard_ok.png", "supported_mortgage_types": ["conventional"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "cecfbb48-b1fe-47a3-8ef6-defc7deda2d5", "name": "FAB - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/FAB%20Business%20Banking/images.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/FAB%20Business%20Banking/images.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "b9490977-295e-46a4-9b28-c72b1d5a80c8", "name": "Ajman Bank - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Ajman%20Bank/Ajmanajman.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Ajman%20Bank/ajman-bank-logo.png", "supported_mortgage_types": [], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "78872584-7784-4be1-8a38-7595ddc6a434", "name": "DIB - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/DIB%20Business%20Banking/dubai_islamic_bank.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/DIB%20Business%20Banking/dubai_islamic_bank_ok.png", "supported_mortgage_types": ["islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "23ff0f0a-2926-49cf-8ad9-a2b089c8fe02", "name": "CBD - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Commercial%20Bank%20of%20Dubai%20Business%20Banking/commercial_bank_of_dubai.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Commercial%20Bank%20of%20Dubai%20Business%20Banking/commercial_bank_of_dubai_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "2d390f77-9dce-4c27-91ef-9efc22bd9409", "name": "SIB - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Sharjah%20Islamic%20Bank/sharjah_islamic_bank.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Sharjah%20Islamic%20Bank/sharjah_islamic_bank_ok.png", "supported_mortgage_types": [], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "7ac40cd4-e13c-4a19-aa41-11433d85c05c", "name": "Emirates Islamic Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Emirates%20Islamic%20Bank/emirates_islamic.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Emirates%20Islamic%20Bank/emirates_islamic_ok.png", "minimum_loan_amount": 200000, "maximum_loan_amount": 5000000, "minimum_account_opening_duration_days": 2, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 5, "valuation_turn_around_time_days": 7, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 24, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "1%", "life_insurance_payment_period": "annually", "property_insurance_payment_period": "annually", "supported_mortgage_types": ["islamic"]},
    {"external_id": "c8fbab5e-90dc-4f07-81a2-802bf9c73594", "name": "Abu Dhabi Islamic Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Abu%20Dhabi%20Islamic%20Bank/ADIBadib.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Abu%20Dhabi%20Islamic%20Bank/adib_ok.png", "minimum_loan_amount": 250000, "maximum_loan_amount": 10000000, "minimum_account_opening_duration_days": 2, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 5, "valuation_turn_around_time_days": 6, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 23, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "30%", "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly", "supported_mortgage_types": ["islamic"]},
    {"external_id": "ddd6cf92-95a3-4282-b545-3ef9b85de07b", "name": "Al Hilal Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Al%20Hilal%20Bank/Al_Hilal.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Al%20Hilal%20Bank/Al_Hilal_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "4724f620-01fd-44f8-9581-6bb003d5188e", "name": "Ajman Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Ajman%20Bank/Ajmanajman.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Ajman%20Bank/ajman-bank-logo.png", "supported_mortgage_types": ["islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "annually"},
    {"external_id": "17f4a5e6-b4d5-4cdb-8e56-b2ac6efada74", "name": "United Arab Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/United%20Arab%20Bank/united_arab_bank.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/United%20Arab%20Bank/united_arab_bank_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "annually"},
    {"external_id": "d34f2317-1945-4f1a-9a0d-cbf680e8934d", "name": "Mashreq - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Mashreq%20Business%20Banking/mashrek.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Mashreq%20Business%20Banking/mashrek_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "65d3212a-4f15-40ca-a344-c7e30091d53e", "name": "MBank - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/MBank%20-%20Business%20Banking/download.jpeg", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/MBank%20-%20Business%20Banking/image.png", "supported_mortgage_types": [], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "d113af44-9d91-4c8c-8fad-fffd8cfedfcf", "name": "EIB - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Emirates%20Islamic%20Bank%20Business%20Banking/emirates_islamic.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Emirates%20Islamic%20Bank%20Business%20Banking/emirates_islamic_ok.png", "supported_mortgage_types": ["islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "eaec0125-c256-4a8f-8811-068f40793b9b", "name": "Emirates Investment Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Emirates%20Investment%20Bank/favicon.ico", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Emirates%20Investment%20Bank/logo.png", "supported_mortgage_types": ["conventional", "islamic"]},
    {"external_id": "516feaa9-846b-4d67-8c23-df153e4bbe43", "name": "Skipton", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Skipton/Skipton.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Skipton/Skipton_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "59421987-1afb-4674-baa8-443885312041", "name": "HSBC", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/HSBC/hsbc.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/HSBC/hsbc_ok.png", "minimum_loan_amount": 350000, "maximum_loan_amount": 35000000, "minimum_account_opening_duration_days": 1, "disbursal_turn_around_days": 4, "fol_turn_around_time_days": 4, "valuation_turn_around_time_days": 6, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 18, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "25%", "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "annually", "supported_mortgage_types": ["conventional", "islamic"]},
    {"external_id": "5da555fc-9855-4ee1-a9cd-25b4f449c113", "name": "ENBD", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/ENBD/enbd_ok.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/ENBD/enbd_logo.png", "minimum_loan_amount": 250000, "maximum_loan_amount": 15000000, "minimum_account_opening_duration_days": 1, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 5, "valuation_turn_around_time_days": 6, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 22, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "1.05%", "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly", "supported_mortgage_types": ["conventional", "islamic"]},
    {"external_id": "b05fa7d0-c35f-4dbc-a097-c1d0227f86b2", "name": "Commercial Bank of Dubai", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Commercial%20Bank%20of%20Dubai/commercial_bank_of_dubai.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Commercial%20Bank%20of%20Dubai/yv3kncbufghagugz9l9r.webp", "minimum_loan_amount": 250000, "maximum_loan_amount": 15000000, "minimum_account_opening_duration_days": 1, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 5, "valuation_turn_around_time_days": 6, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 22, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "15%", "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "annually", "supported_mortgage_types": ["conventional", "islamic"]},
    {"external_id": "9c77a82e-a0dc-4f4d-b506-fc78bdf5c60c", "name": "National Bank of Fujairah", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/National%20Bank%20of%20Fujairah/national_bank_of_fujairah.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/National%20Bank%20of%20Fujairah/national_bank_of_fujairah_ok.png", "minimum_loan_amount": 200000, "maximum_loan_amount": 20000000, "minimum_account_opening_duration_days": 2, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 7, "valuation_turn_around_time_days": 9, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 28, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "1%", "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "annually", "supported_mortgage_types": ["conventional", "islamic"]},
    {"external_id": "c01988fb-cbf6-43ca-896e-87715f42c9f1", "name": "Gatehouse", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Gatehouse/Gatehouse.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Gatehouse/Gatehouse_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "3adda165-37e4-4e32-b29f-bd8d395924aa", "name": "ARAB Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/ARAB%20Bank/arab_bank.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/ARAB%20Bank/arab_bank_ok.png", "minimum_loan_amount": 200000, "maximum_loan_amount": 7300000, "minimum_account_opening_duration_days": 1, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 5, "valuation_turn_around_time_days": 7, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 23, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "25%", "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly", "supported_mortgage_types": ["conventional", "islamic"]},
    {"external_id": "2150285c-8422-4880-a71a-ed1662622957", "name": "Standard Chartered Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Standard%20Chartered%20Bank/standard.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Standard%20Chartered%20Bank/standard_ok.png", "minimum_loan_amount": 300000, "maximum_loan_amount": 18000000, "minimum_account_opening_duration_days": 1, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 4, "valuation_turn_around_time_days": 6, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 21, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "30%", "property_insurance_payment_period": "annually", "supported_mortgage_types": ["conventional", "islamic"]},
    {"external_id": "bb518da7-6a72-4d13-bb65-ba093120f277", "name": "Bank of Baroda", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Bank%20of%20Baroda/bank_of_baroda.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Bank%20of%20Baroda/bank_of_baroda_logo.jpg", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "45195e58-ad22-4d03-a52b-693a6ff65256", "name": "Al Masraf Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Al%20Masraf%20Bank/Al_Masraf.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Al%20Masraf%20Bank/Al_Masraf_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "47be0f96-bb98-4d2e-a375-e6aa5a0b98f9", "name": "ADF", "icon": "", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/ADF/adf_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "791d53fc-0e20-41d7-badd-45eff0857aeb", "name": "Saudi National Bank (former SAMBA)", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Saudi%20National%20Bank%20%28former%20SAMBA%29/snb.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Saudi%20National%20Bank%20%28former%20SAMBA%29/snb_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "ceed08b8-65c0-4762-b54c-f8269043650e", "name": "Mashreq Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Mashreq%20Bank/mashrek.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Mashreq%20Bank/mashrek_ok.png", "minimum_loan_amount": 150000, "maximum_loan_amount": 10000000, "minimum_account_opening_duration_days": 1, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 4, "valuation_turn_around_time_days": 6, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 21, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "25%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "25%", "life_insurance_payment_period": "annually", "property_insurance_payment_period": "annually", "supported_mortgage_types": ["conventional", "islamic"]},
    {"external_id": "4c817d1f-ea52-4392-8dd8-a5712244a55e", "name": "Commercial Bank International", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Commercial%20Bank%20International/CBI.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Commercial%20Bank%20International/cbi_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "2f61684f-81ba-4e21-b361-ce79a1e5c9e6", "name": "HDFC", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/HDFC/hdfc.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/HDFC/HDFC_ok.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "f35c3572-344e-4223-9c20-ac420023ecde", "name": "Citi Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Citi%20Bank/png-clipart-logo-brand-citibank-citigroup-bank-blue-text-thumb.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Citi%20Bank/Citibank-Logo-6.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "f88eeb61-f70e-43ee-8432-2e5670c4ef0a", "name": "Dubai Islamic Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Dubai%20Islamic%20Bank/dubai_islamic_bank.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Dubai%20Islamic%20Bank/dubai_islamic_bank_ok.png", "minimum_loan_amount": 250000, "maximum_loan_amount": 6000000, "minimum_account_opening_duration_days": 1, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 4, "valuation_turn_around_time_days": 6, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 21, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "1%", "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "annually", "supported_mortgage_types": ["islamic"]},
    {"external_id": "234aed4d-0817-4012-8925-4637ec989280", "name": "FAB", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/FAB/images.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/FAB/fab_logo.png", "minimum_loan_amount": 350000, "maximum_loan_amount": 20000000, "minimum_account_opening_duration_days": 2, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 5, "valuation_turn_around_time_days": 7, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 24, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1.05%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "1.05%", "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "annually", "supported_mortgage_types": ["conventional", "islamic"]},
    {"external_id": "f5db47ea-d445-403a-986d-601b2f4f3dd4", "name": "RAKBANK", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/RAKBANK/rakbank.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/RAKBANK/rakbank_ok.png", "minimum_loan_amount": 100000, "maximum_loan_amount": 12000000, "minimum_account_opening_duration_days": 1, "disbursal_turn_around_days": 5, "fol_turn_around_time_days": 5, "valuation_turn_around_time_days": 5, "transfer_turn_around_time_days": 2, "total_expected_turn_around_time_days": 21, "has_early_settlement_fee": True, "early_settlement_fee_percentage": "1%", "has_partial_settlement_fee": True, "partial_settlement_fee_percentage": "20%", "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "annually", "supported_mortgage_types": ["conventional", "islamic"]},
    {"external_id": "aef3f344-7c3c-4115-994a-e2b56a64b694", "name": "Habib Bank AG Zurich", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Habib%20Bank%20AG%20Zurich/image_22.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Habib%20Bank%20AG%20Zurich/image_22.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "94eb409a-58a0-4c65-afc8-3036e29b127b", "name": "National Bank of Umm Al Qaiwain", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/National%20Bank%20of%20Umm%20Al%20Qaiwain/Screenshot_2025-04-28_122702.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/National%20Bank%20of%20Umm%20Al%20Qaiwain/Screenshot_2025-04-28_122702.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "7a7e871d-11dd-4f9d-9a55-4575ca0398af", "name": "Nomo Bank", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Nomo%20Bank/Capture-2024-09-18-122335.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Nomo%20Bank/image_9.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "4da8f57f-2d9e-4151-9ebb-00057dfeefe1", "name": "Invest Bank - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Invest%20Bank%20-%20Business%20Banking/download_1.jpeg", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Invest%20Bank%20-%20Business%20Banking/image_1.png", "supported_mortgage_types": [], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "93d6bdce-50e7-4cee-9c06-7f108be466f3", "name": "ADIB - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Abu%20Dhabi%20Islamic%20Bank%20Business%20Banking/ADIBadib.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/Abu%20Dhabi%20Islamic%20Bank%20Business%20Banking/adib_ok.png", "supported_mortgage_types": [], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
    {"external_id": "534499bc-3e57-4dac-9684-32ce3777417c", "name": "RAK - Business Banking", "icon": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/RAK%20Business%20Banking/rakbank_1.png", "logo": "https://huspy-production-public.s3.amazonaws.com/static/application/bank_entity/RAK%20-%20Business%20Banking/RAK_Logo.png", "supported_mortgage_types": ["conventional", "islamic"], "life_insurance_payment_period": "monthly", "property_insurance_payment_period": "monthly"},
]


def update_banks(apps, schema_editor):
    Bank = apps.get_model('cases', 'Bank')
    # Clear existing banks
    Bank.objects.all().delete()
    # Add all banks
    for bank_data in BANKS_DATA:
        Bank.objects.create(
            external_id=bank_data.get('external_id'),
            name=bank_data.get('name', ''),
            logo=bank_data.get('logo', ''),
            icon=bank_data.get('icon', ''),
            minimum_loan_amount=bank_data.get('minimum_loan_amount'),
            maximum_loan_amount=bank_data.get('maximum_loan_amount'),
            minimum_account_opening_duration_days=bank_data.get('minimum_account_opening_duration_days'),
            disbursal_turn_around_days=bank_data.get('disbursal_turn_around_days'),
            fol_turn_around_time_days=bank_data.get('fol_turn_around_time_days'),
            valuation_turn_around_time_days=bank_data.get('valuation_turn_around_time_days'),
            transfer_turn_around_time_days=bank_data.get('transfer_turn_around_time_days'),
            total_expected_turn_around_time_days=bank_data.get('total_expected_turn_around_time_days'),
            has_early_settlement_fee=bank_data.get('has_early_settlement_fee', False),
            early_settlement_fee_percentage=bank_data.get('early_settlement_fee_percentage', ''),
            has_partial_settlement_fee=bank_data.get('has_partial_settlement_fee', False),
            partial_settlement_fee_percentage=bank_data.get('partial_settlement_fee_percentage', ''),
            life_insurance_payment_period=bank_data.get('life_insurance_payment_period', ''),
            property_insurance_payment_period=bank_data.get('property_insurance_payment_period', ''),
            supported_mortgage_types=bank_data.get('supported_mortgage_types', []),
            is_active=True,
        )


def reverse_update_banks(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_populate_banks'),
    ]

    operations = [
        migrations.RunPython(update_banks, reverse_update_banks),
    ]
