# Generated by Django 4.2.8 on 2026-01-17 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_update_banks_full_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('fully_packaged', 'Fully Packaged'), ('assisted', 'Assisted')], default='fully_packaged', help_text='Case type (Fully Packaged or Assisted)', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='emirate',
            field=models.CharField(choices=[('dubai', 'Dubai'), ('abu_dhabi', 'Abu Dhabi'), ('sharjah', 'Sharjah'), ('ajman', 'Ajman'), ('ras_al_khaimah', 'Ras Al Khaimah'), ('fujairah', 'Fujairah'), ('umm_al_quwain', 'Umm Al Quwain')], default='dubai', help_text='UAE Emirate where property is located', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='fixed_period',
            field=models.CharField(blank=True, choices=[('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('5', '5 Years')], default='', help_text='Fixed rate period in years (if rate type is fixed)', max_length=5),
        ),
        migrations.AddField(
            model_name='case',
            name='mortgage_type',
            field=models.CharField(choices=[('conventional', 'Conventional'), ('islamic', 'Islamic')], default='conventional', help_text='Mortgage type (Conventional or Islamic)', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='property_category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', help_text='Property category (Residential or Commercial)', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='tenure_months',
            field=models.PositiveIntegerField(default=0, help_text='Additional tenure in months (0-11)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='case',
            name='tenure_years',
            field=models.PositiveIntegerField(help_text='Loan tenure in years (1-25)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
