# Generated by Django 4.2.8 on 2026-01-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_add_case_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_first_property',
            field=models.BooleanField(default=True, help_text='Whether this is the first property for LTV calculation'),
        ),
        migrations.AlterField(
            model_name='case',
            name='transaction_type',
            field=models.CharField(choices=[('primary_purchase', 'Primary Purchase'), ('resale', 'Resale'), ('buyout_equity', 'Buyout + Equity'), ('buyout', 'Buyout'), ('equity', 'Equity')], help_text='Transaction type (Purchase, Refinance, Equity Release)', max_length=20),
        ),
    ]
