# Generated by Django 4.2.8 on 2026-01-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_add_is_first_property_to_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='product',
        ),
    ]
