# Generated by Django 4.2.8 on 2026-01-18 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_remove_product_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='stage',
            field=models.CharField(choices=[('processing', 'Processing'), ('submitted_to_bank', 'Submitted to Bank'), ('under_review', 'Under Review'), ('submitted_to_credit', 'Submitted to Credit'), ('valuation_initiated', 'Valuation Initiated'), ('valuation_report_received', 'Valuation Report Received'), ('fol_requested', 'FOL Requested'), ('fol_received', 'FOL Received'), ('fol_signed', 'FOL Signed'), ('disbursed', 'Disbursed'), ('final_documents', 'Final Documents'), ('mc_received', 'MC Received'), ('sales_queries', 'Sales Queries'), ('credit_queries', 'Credit Queries'), ('disbursal_queries', 'Disbursal Queries'), ('on_hold', 'On Hold'), ('property_transferred', 'Property Transferred'), ('rejected', 'Rejected'), ('not_proceeding', 'Not Proceeding')], default='processing', help_text='Current stage of the case', max_length=30),
        ),
        migrations.CreateModel(
            name='StageSLAConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(choices=[('processing', 'Processing'), ('submitted_to_bank', 'Submitted to Bank'), ('under_review', 'Under Review'), ('submitted_to_credit', 'Submitted to Credit'), ('valuation_initiated', 'Valuation Initiated'), ('valuation_report_received', 'Valuation Report Received'), ('fol_requested', 'FOL Requested'), ('fol_received', 'FOL Received'), ('fol_signed', 'FOL Signed'), ('disbursed', 'Disbursed'), ('final_documents', 'Final Documents'), ('mc_received', 'MC Received'), ('sales_queries', 'Sales Queries'), ('credit_queries', 'Credit Queries'), ('disbursal_queries', 'Disbursal Queries'), ('on_hold', 'On Hold'), ('property_transferred', 'Property Transferred'), ('rejected', 'Rejected'), ('not_proceeding', 'Not Proceeding')], help_text='The stage this SLA applies to', max_length=50)),
                ('to_stage', models.CharField(choices=[('processing', 'Processing'), ('submitted_to_bank', 'Submitted to Bank'), ('under_review', 'Under Review'), ('submitted_to_credit', 'Submitted to Credit'), ('valuation_initiated', 'Valuation Initiated'), ('valuation_report_received', 'Valuation Report Received'), ('fol_requested', 'FOL Requested'), ('fol_received', 'FOL Received'), ('fol_signed', 'FOL Signed'), ('disbursed', 'Disbursed'), ('final_documents', 'Final Documents'), ('mc_received', 'MC Received'), ('sales_queries', 'Sales Queries'), ('credit_queries', 'Credit Queries'), ('disbursal_queries', 'Disbursal Queries'), ('on_hold', 'On Hold'), ('property_transferred', 'Property Transferred'), ('rejected', 'Rejected'), ('not_proceeding', 'Not Proceeding')], help_text='The expected next stage', max_length=50)),
                ('sla_hours', models.PositiveIntegerField(help_text='SLA time in hours for this stage transition')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this SLA config is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stage SLA Configuration',
                'verbose_name_plural': 'Stage SLA Configurations',
                'db_table': 'stage_sla_configs',
                'ordering': ['from_stage', 'to_stage'],
                'unique_together': {('from_stage', 'to_stage')},
            },
        ),
    ]
