# Generated by Django 4.2.8 on 2026-01-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_add_stage_sla_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageslaconfig',
            name='breach_percent',
            field=models.PositiveIntegerField(default=120, help_text='Percentage of SLA time at which to escalate to manager (e.g., 120 = escalate at 120% of SLA)'),
        ),
    ]
