# Generated by Django 4.2.8 on 2026-01-18 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_add_breach_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSLAConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sla_type', models.CharField(choices=[('client_to_case', 'Client to Case')], help_text='Type of global SLA', max_length=50, unique=True)),
                ('sla_hours', models.PositiveIntegerField(help_text='SLA time in hours')),
                ('breach_percent', models.PositiveIntegerField(default=120, help_text='Percentage of SLA time at which to escalate to manager')),
                ('description', models.TextField(blank=True, help_text='Description of what this SLA measures')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this SLA config is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global SLA Configuration',
                'verbose_name_plural': 'Global SLA Configurations',
                'db_table': 'global_sla_configs',
            },
        ),
    ]
