# Generated by Django 4.2.8 on 2026-01-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_add_global_sla_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalSLAConfig',
            new_name='ClientToCaseSLAConfig',
        ),
        migrations.AlterModelOptions(
            name='clienttocaseslaconfig',
            options={'verbose_name': 'Client to Case SLA Configuration', 'verbose_name_plural': 'Client to Case SLA Configurations'},
        ),
        migrations.AlterModelTable(
            name='clienttocaseslaconfig',
            table='client_to_case_sla_config',
        ),
    ]
