# Generated by Django 4.2.8 on 2026-01-18
# Migration to add assigned_to field to Case model

from django.db import migrations, models
import django.db.models.deletion


def set_assigned_to_from_created_by(apps, schema_editor):
    """
    Data migration to set assigned_to = created_by for existing cases.
    Since we don't have created_by stored directly, we try to use the audit log.
    If audit log is not available, leave as null.
    """
    Case = apps.get_model('cases', 'Case')
    AuditLog = apps.get_model('audit', 'AuditLog')

    for case in Case.objects.filter(assigned_to__isnull=True):
        # Try to get the creating user from audit log
        audit_entry = AuditLog.objects.filter(
            table_name='cases',
            record_id=case.id,
            action='CREATE'
        ).first()

        if audit_entry and audit_entry.user_id:
            case.assigned_to_id = audit_entry.user_id
            case.save(update_fields=['assigned_to'])


def reverse_set_assigned_to(apps, schema_editor):
    """Reverse migration - set assigned_to to null."""
    Case = apps.get_model('cases', 'Case')
    Case.objects.update(assigned_to=None)


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_rename_global_to_client_to_case_sla'),
        ('users', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        # Add assigned_to field
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                help_text='User assigned to this case',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_cases',
                to='users.user',
            ),
        ),
        # Add index for assigned_to
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_to'], name='cases_assigned_to_idx'),
        ),
        # Data migration to backfill assigned_to from audit log
        migrations.RunPython(set_assigned_to_from_created_by, reverse_set_assigned_to),
    ]
