# Generated by Django 4.2.8 on 2026-01-13 09:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisition_channels', '0004_add_source_sla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the lead', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the lead', max_length=255)),
                ('phone', models.CharField(help_text='Phone number of the lead', max_length=20)),
                ('email', models.EmailField(blank=True, default='', help_text='Email address (optional)', max_length=255)),
                ('intent', models.TextField(blank=True, default='', help_text='Notes about the lead intent (optional)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('declined', 'Declined'), ('not_proceeding', 'Not Proceeding')], default='active', help_text='Current status of the lead', max_length=20)),
                ('converted_client_id', models.UUIDField(blank=True, help_text='Client record ID created when lead was converted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when lead was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when lead was last updated')),
                ('sub_source', models.ForeignKey(help_text='Sub-source this lead came from (must be untrusted channel)', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='acquisition_channels.subsource')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='leads_status_idx'), models.Index(fields=['sub_source'], name='leads_sub_source_idx'), models.Index(fields=['created_at'], name='leads_created_at_idx')],
            },
        ),
    ]
