# Generated by Django 5.2.10 on 2026-01-20 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_channels', '0004_add_source_sla'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('template_sent', 'Template Sent'), ('button_click', 'Button Click'), ('text_reply', 'Text Reply'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('status_change', 'Status Change')], help_text='Type of interaction', max_length=20)),
                ('ycloud_message_id', models.CharField(blank=True, default='', help_text='YCloud message ID (for replies)', max_length=255)),
                ('original_message_id', models.CharField(blank=True, default='', help_text='ID of the message being replied to (context.id)', max_length=255)),
                ('template_name', models.CharField(blank=True, default='', help_text='Template name if template_sent or reply to template', max_length=255)),
                ('content', models.TextField(blank=True, default='', help_text='Message content or button payload')),
                ('tag_value', models.CharField(blank=True, default='', help_text='Tag value for tag_added/tag_removed interactions', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data from webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('button', 'Button'), ('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('content', models.TextField(help_text='Message content/body')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ycloud_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('button_payload', models.CharField(blank=True, default='', max_length=255)),
                ('template_name', models.CharField(blank=True, default='', max_length=255)),
                ('reply_to_message_id', models.CharField(blank=True, default='', help_text='YCloud message ID this is a reply to', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lead_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign_status',
            field=models.CharField(choices=[('subscriber_pending', 'Subscriber Pending'), ('segment_mortgaged', 'Mortgaged'), ('segment_renting', 'Renting'), ('segment_other', 'Other Segment'), ('locale_dubai', 'Dubai'), ('locale_abudhabi', 'Abu Dhabi'), ('locale_other', 'Other Locale'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('converted', 'Converted')], default='subscriber_pending', help_text='Derived campaign status from tags (highest priority)', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_tags',
            field=models.JSONField(blank=True, default=list, help_text='Current list of YCloud tags assigned to this lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='When the lead first responded to a campaign', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_response_at',
            field=models.DateTimeField(blank=True, help_text='When the lead last responded', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='response_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of responses from this lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ycloud_contact_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='YCloud contact ID for this lead', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('declined', 'Declined')], default='active', help_text='Current status of the lead', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['campaign_status'], name='leads_campaign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['ycloud_contact_id'], name='leads_ycloud_contact_idx'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='lead',
            field=models.ForeignKey(help_text='Lead this interaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadmessage',
            name='lead',
            field=models.ForeignKey(help_text='Lead this message is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['lead', 'created_at'], name='lead_interaction_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['interaction_type'], name='lead_interaction_type_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmessage',
            index=models.Index(fields=['lead', 'created_at'], name='lead_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmessage',
            index=models.Index(fields=['ycloud_message_id'], name='lead_msg_ycloud_idx'),
        ),
    ]
