# Generated by Django 4.2.8 on 2026-01-13 03:15

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('supabase_auth_id', models.UUIDField(blank=True, help_text='Supabase Auth user ID for authentication integration', null=True, unique=True)),
                ('username', models.CharField(help_text='Username for login', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='User email address', max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('name', models.CharField(help_text='Full name of the user for display', max_length=255)),
                ('password_hash', models.CharField(blank=True, default='', help_text='SHA256 hash of password for local auth', max_length=64)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('mortgage_specialist', 'Mortgage Specialist'), ('process_executive', 'Process Executive')], help_text='User role determining access permissions', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user can log in (soft delete mechanism)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when user was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when user was last updated')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='users_role_idx'), models.Index(fields=['is_active'], name='users_is_active_idx')],
            },
        ),
    ]
