# Generated by Django 5.2.10 on 2026-01-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('channel_owner', 'Channel Owner'), ('team_leader', 'Team Leader'), ('mortgage_specialist', 'Mortgage Specialist'), ('process_officer', 'Process Officer')], help_text='User role determining access permissions', max_length=20),
        ),
    ]
