# Generated by Django 5.2.10 on 2026-01-29 12:47

from django.db import migrations


def migrate_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    # Rename process_executive -> process_officer
    User.objects.filter(role='process_executive').update(role='process_officer')
    # Convert manager -> channel_owner
    User.objects.filter(role='manager').update(role='channel_owner')


def reverse_migrate_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='process_officer').update(role='process_executive')
    User.objects.filter(role='channel_owner').update(role='manager')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_update_user_roles'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_migrate_roles),
    ]
