# Generated by Django 5.2.10 on 2026-01-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('cases', '0013_add_case_assigned_to'),
        ('clients', '0009_swap_subsource_to_source'),
        ('leads', '0003_swap_subsource_to_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case this note is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_notes', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='note',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client this note is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_notes', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='note',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Lead this note is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_notes', to='leads.lead'),
        ),
    ]
